OPPONENT_ROCK = "A"
OPPONENT_PAPER = "B"
OPPONENT_SCISSORS = "C"

PLAYER_ROCK = "X"
PLAYER_PAPER = "Y"
PLAYER_SCISSORS = "Z"

VALID_SHAPES = [OPPONENT_ROCK, OPPONENT_PAPER, OPPONENT_SCISSORS, PLAYER_ROCK, PLAYER_PAPER, PLAYER_SCISSORS]

WIN_SCORE = 6
DRAW_SCORE = 3
LOSS_SCORE = 0

LOSE = "X"
DRAW = "Y"
WIN = "Z"

ROCK_SCORE = 1
PAPER_SCORE = 2
SCISSORS_SCORE = 3


ROUND_COMBINATIONS = {
    OPPONENT_ROCK: {WIN: PLAYER_PAPER, LOSE: PLAYER_SCISSORS, DRAW: PLAYER_ROCK},
    OPPONENT_PAPER: {WIN: PLAYER_SCISSORS, LOSE: PLAYER_ROCK, DRAW: PLAYER_PAPER},
    OPPONENT_SCISSORS: {WIN: PLAYER_ROCK, LOSE: PLAYER_PAPER, DRAW: PLAYER_SCISSORS}
}
